name: version-command

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "SemVer bump"
        required: true
        type: choice
        options: [patch, minor, major]
      ref:
        description: "The branch this workflow file runs from (dispatcher supplied)"
        required: true
        type: string
      target:
        description: "PR head branch to update (dispatcher supplied)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head branch (use PAT so push re-triggers CI)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target }}
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - run: pnpm install --frozen-lockfile

      - name: Apply npm version bump (no tag)
        run: |
          npm version ${{ inputs.bump }} --no-git-tag-version -m "chore(version): %s"

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          git commit -m "chore(version)" || echo "No changes"
          git push origin HEAD
